### ISSUE TITLE
Cannot locate native library 'liblinenoise.so'

### ISSUE THREAD

**Issue by perlpilot** [hoelzro/p6-linenoise#1]
After a fresh install of rakudo, the REPL works fine.  But then after installing Linenoise via panda, I get:

➤ perl6
===SORRY!===
Cannot locate native library 'liblinenoise.so'

I imagine that it's only the documentation aspect that can really be improved here.  For unixy OSen, updating LD_LIBRARY_PATH to contain the path where liblinenoise.so is installed works, but I'm not sure what one would do on Windows or a Mac.

**Comment by hoelzro** [comment]
@perlpilot Thanks for the report; I thought that CURLIs still had issues to resolve around this, but that appears to be fixed!  I'll update the docs to reflect this.

**Comment by hoelzro** [comment]
This is fixed in the latest MoarVM.
