### ISSUE TITLE
Linenoise not installing cleanly from Pando on Win32 R* 2016.01

### ISSUE THREAD

**Issue by fecundf** [hoelzro/p6-linenoise#13]
I noted on the user-experience page that LineNoise wasn't installing for my rakudo*... here is the full output from my attempt, using the 32-bit Rakudo \* from the official ".msi" (on a 32-bit Windows 10 laptop). in this case it depended on nmake which I must not have.

FWIW, I do have Strawberry Perl installed and in the path, it provides C:\Strawberry\c\bin\gmake.exe and other compiler tools.

Perhaps a check for the compiler tools and a more informative error message?

> `perl6 -v`
> This is Rakudo version 2016.01.1 built on MoarVM version 2016.01
> implementing Perl 6.c.
> 
> `panda install Linenoise`

==> Linenoise depends on Native::Resources
==> Native::Resources depends on LibraryMake
==> Fetching LibraryMake
==> Building LibraryMake
==> Testing LibraryMake
'nmake' is not recognized as an internal or external command, operable program or batch file.
The spawned process exited unsuccessfully (exit code: 1)
  in block <unit> at t/01-basic.t line 20

# Looks like you planned 7 tests, but ran 4
t/01-basic.t ..
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 3/7 subtests

Test Summary Report
-------------------
t/01-basic.t (Wstat: 65280 Tests: 4 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 7 tests but ran 4.
Files=1, Tests=4,  5 wallclock secs ( 0.05 usr +  0.01 sys =  0.06 CPU)
Result: FAIL
The spawned process exited unsuccessfully (exit code: 1)
  in sub run-and-gather-output at C:\rakudo\share\perl6\site\sources\5AEF9DA5AE15E5AB5CB2ADB58A455E007FA7839E line 85
  in block  at C:\rakudo\share\perl6\site\sources\FB10E7A100D50F6DB505EC4DC538BEAB5154DED3 line 22
  in sub indir at C:\rakudo\share\perl6\site\sources\5AEF9DA5AE15E5AB5CB2ADB58A455E007FA7839E line 20
  in method test at C:\rakudo\share\perl6\site\sources\FB10E7A100D50F6DB505EC4DC538BEAB5154DED3 line 5
  in method install at C:\rakudo\share\perl6\site\sources\9036849E1656E91211D00AB4530B81D29A7D6E82 line 156
  in block  at C:\rakudo\share\perl6\site\sources\9036849E1656E91211D00AB4530B81D29A7D6E82 line 229
  in method resolve at C:\rakudo\share\perl6\site\sources\9036849E1656E91211D00AB4530B81D29A7D6E82 line 223
  in sub MAIN at C:\rakudo\share\perl6\site/resources/76CD539C815A33F2891D2EF3D6D96B1081567AD1 line 18
  in block <unit> at C:\rakudo\share\perl6\site/resources/76CD539C815A33F2891D2EF3D6D96B1081567AD1 line 150

**Comment by hoelzro** [comment]
@fecundf Thanks for the report; I have a feeling that the Rakudo msi was built with nmake, so Rakudo's internal configuration probably is telling Linenoise to use nmake to build itself.

Could you post the results of the following?

``` perl6
.say for $*VM.config.pairs.sort(*.key)
```

**Comment by fecundf** [comment]
Posted it at https://gist.github.com/fecundf/4fa92bb4e07eed758112

Also, a few months ago I went thru the trouble of building rakudo/Moar using the gcc toolchain included with Strawberry Perl on this same machine; I have bits and pieces from that mixed in with the 2016.01 R*. I am about to delete all my Rakudo directories and re-install from the MSI to have a clean install..

**Comment by hoelzro** [comment]
@fecundf Judging from the output, it looks like my hypothesis is true.  We'll find out for sure when you re-install.

**Comment by fecundf** [comment]
Cleaned out my old rakudo directory, used the uninstall control panel to remove old Rakudo as well, did a clean install of 64-bit R\* 2016.01, and same error of it looking for nmake and not installing Linenoise.

**Comment by fecundf** [comment]
ps. when I first opened this, I was using a 32-bit Windows laptop, now I am on a 64-bit Windows laptop. Same error on both architectures.

**Comment by hoelzro** [comment]
@fecundf Thanks for checking; I'll talk with some of the other developers and see what we can do to address this.

**Comment by hoelzro** [comment]
This is over two years old and Panda is (to my knowledge) no longer supported; I'm going to go ahead and close this.
