### ISSUE TITLE
Auto-complete still needs improvement

### ISSUE THREAD

**Issue by Altai-man** [hoelzro/p6-linenoise#14]
Sorry, I'm not aware about state of the project, and it's hard to distinguish underlying library troubles with wrapper library troubles, but anyway.

With latest rakudo, moarvm/nqp, latest Linenoise is unable to process tab pressing correctly. While auto-complete with empty line is fine like this:

```
➜  ~ perl6
To exit type 'exit' or '^D'
> Array # Two tab hits.
(Array)
> 
```

it can't write actual tab character itself in string literal:

```
> " # Hit tab once and this string will become like this:
> "Use of uninitialized value $v of type Any in string context
                                                              Any of .^name, .perl, .gist, or .say can stringify undefined things, if needed.  in method CALL-ME at /home/sena/.rakudobrew/moar-nom/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 303
              Use of uninitialized value $v of type Any in string context
                                                                         Any of .^name, .perl, .gist, or .say can stringify undefined things, if needed.  in method CALL-ME at /home/sena/.rakudobrew/moar-nom/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 303
> Any
```

If I by hands copy-paste tab character, output will be the same.
Is it a known issue?

**Comment by hoelzro** [comment]
@Altai-man So the problem is that you can't use the tab character to insert a literal TAB character into a string?

**Comment by Altai-man** [comment]
@hoelzro right, exactly. I wanted to know is it just mine problem and a bug or it's just "work in progress".

**Comment by hoelzro** [comment]
This is a limitation of how aware of the context rakudo's usage of this library is.  The REPL isn't quite smart enough to know if it's in a string or not.  I would like for the REPL to be smarter about the context of the code, but that's no small task.  It's not really Linenoise's fault, though.

**Comment by Altai-man** [comment]
I suppose you already thought about it, but can we in the REPL wrapper code look at the previous character before cursor? If so, we can check is it nothing(e.g. start of line) or space, and don't complete it(since it's probably meaningless), and when we have some character(s) before - to do an attempt to complete it then. Just a pure concept.

**Comment by hoelzro** [comment]
@Altai-man Rakudo already does some rudimentary checking; I don't know if removing completions mid-line is a good idea, though.  Imagine if someone types the following:

```
> my $s = Str.sub<TAB>
```

Now, Rakudo doesn't implement this (yet), but I would love for the REPL to offer `Str` methods that begin with `sub` to the user.  What Rakudo _does_ implement is completion of class names.

Either way, that's an issue for Rakudo, not for Linenoise.

**Comment by Altai-man** [comment]
Ah, I understand now. Yes, then it's definitely time to wait for rakudo changes. Obviously, can be closed.
