### ISSUE TITLE
Segmentation Fault When Typing Verbatim Tabs

### ISSUE THREAD

**Issue by webstrand** [hoelzro/p6-linenoise#18]
To reproduce, enter two consecutive verbatim tabs (ctrl-v tab) and the process dies with SIGSEGV.

I built moarvm, nqp, and rakudo from git at tag 2016.12 with gcc 6.2.1 and clang 3.9.1 on up-to-date Archlinux.

Backtrace:

    #0  0x00007ffff7921bdb in callback_handler (cif=<optimized out>, cb_result=<optimized out>, cb_args=<optimized out>, cb_data=0x334b4b0) at src/core/nativecall_libffi.c:251
    #1  0x00007ffff7203fbf in ffi_closure_unix64_inner () from //usr/lib/libffi.so.6
    #2  0x00007ffff7204330 in ffi_closure_unix64 () from //usr/lib/libffi.so.6
    #3  0x00007ffff42452eb in linenoise () from /home/user/.perl6/resources/DEEB27B5853BA6C98B824267B82369F02D44CB2F.so
    #4  0x00007ffff72041c8 in ffi_call_unix64 () from //usr/lib/libffi.so.6
    #5  0x00007ffff7203c2a in ffi_call () from //usr/lib/libffi.so.6
    #6  0x00007ffff7923443 in MVM_nativecall_invoke (tc=0x6037c0, res_type=<optimized out>, site=<optimized out>, args=<optimized out>) at src/core/nativecall_libffi.c:590
    #7  0x00007ffff78fe012 in MVM_interp_run (tc=tc@entry=0x6037c0, initial_invoke=0xe, invoke_data=0x12) at src/core/interp.c:3968
    #8  0x00007ffff79a1459 in MVM_vm_run_file (instance=0x603010, filename=0x7fffffffe572 "/usr/share/perl6/runtime/perl6.moarvm") at src/moar.c:309
    #9  0x0000000000400ed9 in main (argc=6, argv=0x7fffffffe208) at src/main.c:192

**Comment by hoelzro** [comment]
@webstrand Hi there! Thanks for reporting the issue - I just tried it on the latest MoarVM, NQP, and Rakudo, and I can't reproduce the error there (using gcc 6.2.1 on up-to-date Arch as well).  Could you try building Rakudo from nom and see if you can reproduce the problem there?

**Comment by hoelzro** [comment]
@webstrand Are you still able to reproduce the issue?

**Comment by hoelzro** [comment]
(bump)
