### ISSUE TITLE
Build failing while installing Linenoise

### ISSUE THREAD

**Issue by sumanstats** [hoelzro/p6-linenoise#22]
Hi there,

I am trying to install Linenoise in [this docker image](https://hub.docker.com/r/sumdoc/perl-6/).
But the build is failing and throwing this error:
```
root@6c2270698b37:/# zef install Linenoise
===> Searching for: Linenoise
===> Searching for missing dependencies: LibraryMake
===> Searching for missing dependencies: Shell::Command
===> Searching for missing dependencies: File::Which, File::Find
===> Building: Linenoise:ver('0.1.1'):auth('Rob Hoelz')
===> Building [FAIL]: Linenoise:ver('0.1.1'):auth('Rob Hoelz')
Aborting due to build failure: Linenoise:ver('0.1.1'):auth('Rob Hoelz') (use --force-build to override)
  in code  at /usr/share/perl6/site/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 331
  in method build at /usr/share/perl6/site/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 296
  in sub  at /usr/share/perl6/site/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 522
  in method install at /usr/share/perl6/site/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 633
  in sub MAIN at /usr/share/perl6/site/sources/31FF9E8498781BF95868DF98AD861FCF1211BCC1 (Zef::CLI) line 152
  in block <unit> at /usr/share/perl6/site/resources/0031ECC6124802A80F7B7B073C50D0A1694E3020 line 1
  in sub MAIN at /usr/share/perl6/site/bin/zef line 2
  in block <unit> at /usr/share/perl6/site/bin/zef line 2
```

I couldn't make out anything from error message.

Any help!!

Best,
Suman

**Comment by sumanstats** [comment]
It got resolved after installing`apt-get build essential`.
This was the dockerfile.
```
FROM debian:sid
WORKDIR /

RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential \
  git nano libzmq3-dev libreadline-dev ca-certificates\
  && rm -rf /var/lib/apt/lists/* \
  && git clone https://github.com/rakudo/rakudo.git \
  && cd rakudo && perl Configure.pl --prefix=/usr --gen-moar --gen-nqp --backends=moar \
  && make && make install && cd .. && rm -rf rakudo \
  && apt-get purge -y --auto-remove build-essential 


RUN git clone https://github.com/ugexe/zef.git && cd zef && perl6 -I. bin/zef install . && cd .. && rm -rf zef
ENV PATH /usr/share/perl6/site/bin:$PATH


CMD ["perl6", "--version"]
```
Now I am going to modify the docker image.

Thanks,

**Comment by hoelzro** [comment]
@sumandoc Since you worked out the problem, is it ok to close this issue?

**Comment by sumanstats** [comment]
@hoelzro Yes. 

I would highly recommend to mention the exact dependencies of `Linenoise` in `README` file, because I get it to working after installing `apt-get install build-essential` which of course brings many unwanted tools along with it. 
This package is a requirement while making [this image](https://hub.docker.com/r/sumdoc/perl-6-notebook/). I even [wrote a blog on it ](https://sumdoc.wordpress.com/2017/09/06/how-to-run-perl-6-notebook/).

And would love to see `UTF-8 ` support in this package. 

Best,
Suman

**Comment by hoelzro** [comment]
@sumandoc Thanks for the tip - I'll add a notice about `build-essential` to the README.  UTF-8 support is present in a branch (see #20), but I need some features in LibraryMake in order to merge it.
