### ISSUE TITLE
When building on Windows in the Cmder (or possibly msys), the build script invokes Linux commands

### ISSUE THREAD

**Issue by lefth** [hoelzro/p6-linenoise#23]
I'm inclined to say that even though there is a "sh" command available, all windows builds should be treated as pure windows builds, and not invoke bash scripts. (Rakudo doesn't currently build for Cygwin, and msys/Cmder are simply a more friendly interface to native Windows executables.)

Note that when I re-ran the build in cmd.exe, it worked without error.

Output:
===> Building: Linenoise:ver<0.1.1>:auth<Rob Hoelz>
/usr/bin/sh: perl6: command not found
gmake: *** [C:\Users\user\.zef\store\p6-linenoise.git\480fd919b2c082e691c518fd50c19ad8719532b6/resources/libraries/linenoise.dll] Error 127

**Comment by hoelzro** [comment]
I'm guessing this is the doing of `make` - I'm only really familiar with using `make` to build things, so if you have a suggestion on how I could build the necessary binary components without using make on Windows, I would really appreciate it!

**Comment by lefth** [comment]
It does work on Windows, but only in the main CMD.exe command shell. I'll
have a look and see if I can tell why "sh" is being invoked.

**Comment by lefth** [comment]
I can't find the cause. This is surely a bug in make, or possibly the way Cmder invokes make. I'm closing this, because in either case, it's not something you can reasonably fix.

**Comment by hoelzro** [comment]
I don't think it's a bug in make - make happens to invoke sh to execute commands.  The only way I can see this being fixed, however, is to not use make.  The makefile isn't terribly complicated, fortunately, so maybe we could invoke the commands directly in Perl 6.

**Comment by lefth** [comment]
Make invokes sh on Windows as well? If that's the case, it could be that
Cmder is losing/changing the PATH variable. I'll look at that next week,
and also compare behavior with the other two related console emulators:
Cmder lite (without unix executables), and ConEmu.
