### ISSUE TITLE
Linenoise warning on Windows 10 with 2018.04.1

### ISSUE THREAD

**Issue by stmuk** [hoelzro/p6-linenoise#24]
```
C:\Windows\system32>perl6                                                                                              
I ran into a problem while trying to set up Linenoise: Must specify something as a path: did you mean '.' for the current directory?                                                                                                            
Continuing without tab completions or line editor                                                                       
```

**Comment by hoelzro** [comment]
This is a rakudobug; I have submitted a fix as a PR: https://github.com/rakudo/rakudo/pull/1934

**Comment by hoelzro** [comment]
The PR has been merged; please test this out with the latest Rakudo from master and let me know if it's still an issue!

**Comment by hoelzro** [comment]
@stmuk Could you try this again on a Rakudo built from master to verify the fix?

**Comment by hoelzro** [comment]
Since the error message is the exact same and the fix was not platform-specific, I'm going to close this issue.  Please re-open if it presents itself in the future!

**Comment by boris-mb** [comment]
PS C:\boris> zef install Linenoise --force-install
===> Searching for: Linenoise
Enabled extracting backends [path tar psunzip] don't understand C:\Users\new_d/.zef/tmp\1540408292.5748.7603\p6-linenoise.git
You may need to configure one of the following backends, or install its underlying software - [git p5tar unzip]

**Comment by hoelzro** [comment]
@boris-mb Thanks for the report - that looks more like an issue with `zef` trying to make sense of the Linenoise repository rather than a Linenoise build problem; do other modules install ok?
