### ISSUE TITLE
Broken on Windows 2018.06 

### ISSUE THREAD

**Issue by stmuk** [hoelzro/p6-linenoise#26]
````
I ran into a problem while trying to set up Linenoise: Must specify something as a path: did you mean '.' for the current directory?
Continuing without tab completions or line editor
````

**Comment by hoelzro** [comment]
@stmuk This reminds me of #24 - did you happen to see if my [fix back in June](https://github.com/rakudo/rakudo/commit/91b211ac2) fixed that issue on Windows?  If it didn't, then I'm guessing it's related to that; if it did, I'll start investigating elsewhere.

**Comment by hoelzro** [comment]
@stmuk This should be all fixed on master now!

**Comment by stmuk** [comment]
👍
