### ISSUE TITLE
https://github.com/rakudo/rakudo/issues/5087

### ISSUE THREAD

**Issue by jubilatious1** [hoelzro/p6-linenoise#37]
https://github.com/rakudo/rakudo/issues/5087

@hoelzro

**Comment by JJ** [comment]
Possibly a LibraryMake dependency? Only one there...

**Comment by JJ** [comment]
Got lost getting to [File::Which](https://raku.land/github:azawawi/File::Which) I have no idea where that dependency comes from. Can we maybe get the whole dep tree with the module Will Coleda created?

**Comment by JJ** [comment]
That one is [not working in Windows](https://github.com/azawawi/raku-file-which/actions/runs/3116942115/jobs/5055214660) anyway.

**Comment by patrickbkr** [comment]
I'm pretty sure this has nothing to do with linenoise. I'm closing this issue in favor of https://github.com/rakudo/rakudo/issues/5087

**Comment by JJ** [comment]
How come it not have anything to do with Linenoise if it's literally happening when installing Linenoise?

**Comment by patrickbkr** [comment]
I now (manually) traced through the dependency tree:
linenoise -> LibraryMake -> Shell::Command -> File::Which

It would have been a very hideous bug in linenoise (and it's META6.json) that manages to establish a dependency on Win32::Registry without being obvious in its META6.json. That's why I said that I'm pretty sure it's not linenoises fault after having looked at its META6.json and remembering the File::Which issue that is discussed over in https://github.com/rakudo/rakudo/issues/5087.

**Comment by JJ** [comment]
> I now (manually) traced through the dependency tree: linenoise -> LibraryMake -> Shell::Command -> File::Which
> 
> It would have been a very hideous bug in linenoise (and it's META6.json) that manages to establish a dependency on Win32::Registry without being obvious in its META6.json. That's why I said that I'm pretty sure it's not linenoises fault after having looked at its META6.json and remembering the File::Which issue that is discussed over in [rakudo/rakudo#5087](https://github.com/rakudo/rakudo/issues/5087).

Thanks for the explanation.

**Comment by jubilatious1** [comment]
I cross-posted this with the Rakudo repo because it's such an important bug. 

If bugs like this can occur with critical modules, people won't adopt the language and ecosystem.

Is there any way of protecting Raku Community Modules that provide critical infrastructure?

The top 3 Raku/Rakudo modules in my mind are:

1. zef
2. Readline
3. Linenoise

Assuming here that the problem is with the `Win32::Registry` module.

**Comment by patrickbkr** [comment]
IMHO the fundamental problem is the suboptimal behavior of P6C that introduces a hard to track and control mutability into installations. The way forward we as a community have decided on is deprecating P6C and moving forward with the zef/fez ecosystem.
See https://github.com/Raku/problem-solving/pull/318/files
I'll have to follow up how the REA harvester deals with version numbers and whether the p6c ecosystem is actually disabled in current zef. But apart from that the problems revolving around p6c should soon(TM) go away together with p6c.
